# Configure dependabot to automatically open PRs for bumping the hard pin of pydata-sphinx-theme

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: "increase"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "pydata-sphinx-theme"
