language: python

python:
  - 3.6

before_install:
  - npm install -g stylelint
  - npm install stylelint-config-recommended
  - stylelint ./sunpy_sphinx_theme/sunpy/static/style.css

install:  
  - pip install -e .
  - git clone https://github.com/sunpy/sunpy.github.io.git
  - cd sunpy.github.io
  - pip install -r requirements.txt

script:
  - make html
  - rm ./_build/html/CNAME
  - pwd

deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip_cleanup: true
  github_token: $mytoken
  local_dir: /home/travis/build/sunpy/sunpy-sphinx-theme/sunpy.github.io/_build/html/
  on:
    branch: master
