version: 2.1

apt-run: &apt-install
  name: Install apt packages
  command: |
    sudo apt update
    sudo apt install -y graphviz pandoc

pip-run: &pip-install
  name: Install Python dependencies
  command: |
    python3 -m venv venv
    echo "source /home/circleci/project/venv/bin/activate" >> $BASH_ENV

jobs:

  website:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: *apt-install
      - run: *pip-install
      - run: pip install -U setuptools | cat
      - run: pip install -e . | cat
      - run: git clone https://github.com/sunpy/sunpy.org.git
      - run: pip install -r sunpy.org/requirements.txt | cat
      - run: make -C $HOME/project/sunpy.org html
      - store_artifacts:
          path: sunpy.org/_build/html
      - run:
          name: "Built documentation is available at:"
          command: DOCS_URL="${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/sunpy.org/_build/html/index.html"; echo $DOCS_URL

  docs:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: *apt-install
      - run: *pip-install
      - run: pip install -U setuptools | cat
      - run: pip install -e . | cat
      - run: pip install sunpy[dev] | cat
      - run: cd test_package && pip install -e . && cd docs && make html
      - store_artifacts:
          path: test_package/docs/_build/html
      - run:
          name: "Built documentation is available at:"
          command: DOCS_URL="${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/test_package/docs/_build/html/index.html"; echo $DOCS_URL

  linting:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: sudo npm install -g stylelint
      - run: sudo npm install stylelint-config-recommended
      - run: sudo stylelint ./sunpy_sphinx_theme/sunpy/static/sunpy_style.css


workflows:
  version: 2

  docs:
    jobs:
      - docs
  website:
    jobs:
      - website
  linting:
    jobs:
      - linting

notify:
  webhooks:
    - url: https://giles.cadair.dev/circleci
